### ISSUE TITLE
panic: interface conversion

### ISSUE THREAD

**Issue by noma4i** [wallix/awless#90]
AWS admin role user.
Go: `go version go1.8.1 darwin/amd64`
Fresh install awless via `brew tap wallix/awless; brew install awless`
Command: `awless list buckets`
Result: `showing my s3 buckets as intended`

Command: `awless inspect -i bucket_sizer`
Result:
````
[info]    Running full sync before inspection (disable it with --local flag)

panic: interface conversion: interface {} is int, not float64

goroutine 1 [running]:
github.com/wallix/awless/inspect/inspectors.(*BucketSizer).Inspect(0xc420177fb0, 0xc420efa730, 0x0, 0x8)
	/private/tmp/awless-20170505-20515-131iloe/src/github.com/wallix/awless/inspect/inspectors/bucket_sizer.go:51 +0x373
github.com/wallix/awless/commands.glob..func6(0x29adce0, 0xc420276440, 0x0, 0x2, 0x0, 0x0)
	/private/tmp/awless-20170505-20515-131iloe/src/github.com/wallix/awless/commands/inspect.go:71 +0x2e5
github.com/wallix/awless/vendor/github.com/spf13/cobra.(*Command).execute(0x29adce0, 0xc4202762a0, 0x2, 0x2, 0x29adce0, 0xc4202762a0)
	/private/tmp/awless-20170505-20515-131iloe/src/github.com/wallix/awless/vendor/github.com/spf13/cobra/command.go:646 +0x3ef
github.com/wallix/awless/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x29acbe0, 0xc420199f78, 0x100645c, 0xc420074058)
	/private/tmp/awless-20170505-20515-131iloe/src/github.com/wallix/awless/vendor/github.com/spf13/cobra/command.go:737 +0x339
github.com/wallix/awless/vendor/github.com/spf13/cobra.(*Command).Execute(0x29acbe0, 0x0, 0x0)
	/private/tmp/awless-20170505-20515-131iloe/src/github.com/wallix/awless/vendor/github.com/spf13/cobra/command.go:695 +0x2b
github.com/wallix/awless/commands.ExecuteRoot(0xc420000340, 0xc420000340)
	/private/tmp/awless-20170505-20515-131iloe/src/github.com/wallix/awless/commands/root.go:69 +0x31
main.main()
	/private/tmp/awless-20170505-20515-131iloe/src/github.com/wallix/awless/main.go:22 +0x22
````

**Comment by simcap** [comment]
Hi @noma4i . Thanks for reporting. This is now fixed on master. You can use it with a regular `go get -u` or a `git pull; go install` according to your set up.

**Comment by noma4i** [comment]
I will wait for a tagged release in brew ;) hate dealing with define gopath. ;)
